name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      # Install Node dependencies
      - run: npm ci

      # Install Ruby dependencies
      - run: bundle install

      # Lint
      - run: npm run lint

      # TypeScript type check
      - run: npx tsc --noEmit

      # Build Jekyll
      - run: bundle exec jekyll build

      # Build Next.js/TinaCMS
      - run: npm run build

      # Upload GitHub Pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    needs: build-and-lint
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v2
